export const USERLOADING="USERLOADING"
export const REGISTERSUCCESS="REGISTERSUCCESS"
export const REGISTERFAILED="REGISTERFAILED"

export const LOGINSUCCESS="LOGINSUCCESS"
export const LOGINFAILED="LOGINFAILED"
export const USERSUCCESS="USERSUCCESS"
export const USERFAILED="USERFAILED"


export const LOGOOUT="LOGOOUT"

